piVersion: apps/v1
kind: Deployment
metadata:
  name: helm-weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-weather-app
  template:
    metadata:
      labels:
        app: helm-weather-app
    spec:
      containers:
      - name: helm-weather-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
